#!/usr/bin/awk -f

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyrigth © Alexander Ben Nasrallah 2017 <abn@posteo.de>

{
	iter = $3
	color = "black"

	if (iter < 5) {
		color = "midnight blue"
	} else if (iter < 10) {
		color = "dark slate blue"
	} else if (iter < 12) {
		color = "medium slate blue"
	} else if (iter < 15) {
		color = "royal blue"
	} else if (iter < 18) {
		color = "blue"
	} else if (iter < 20) {
		color = "dodger blue"
	} else if (iter < 25) {
		color = "deep sky blue"
	} else if (iter < 30) {
		color = "sky blue"
	} else if (iter < 100) {
		color = "light sky blue"
	} else {
		color = "black"
	}

	print $1","$2","color
}
